language: python
python:
  - "3.5.2"

install:
  # python dependencies
  - pip install -r backend/requirements.txt
  - pip install -r backend/requirements-dev.txt
  - pip install coveralls --quiet

script:
  - cd backend
  - python -m tests.run

after_success: coveralls